baseURL = "https://www.jessemostipak.com/"
title = "☙❦ Jesse Mostipak ❦❧"
theme = "hugo-bearblog"
copyright = "Jesse Mostipak"

[params]
  author = "Jesse Mostipak"
  description = "Revenue Architect & Technical Storyteller"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "The Scriptorium"
    url = "/blog"
    weight = 2
[[menu.main]]
    name = "The Studio"
    url = "/studio"
    weight = 3
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
